### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by kunalkushwaha** [kubevirt/client-go#2]
Need some examples to show how to use go-client.

**Comment by slintes** [comment]
Good idea, thanks.
Until we we have something in place, you might want to have a look the at the tests in the kubevirt/kubevirt repository, there we use the client a lot, e.g. starting here: https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_lifecycle_test.go#L78

**Comment by kunalkushwaha** [comment]
I have few examples, but how to add them in this repo? I guess it will be
overwritten by CI.

**Comment by slintes** [comment]
That would be great, thanks! This is a copy of https://github.com/kubevirt/kubevirt/tree/master/staging/src/kubevirt.io/client-go, you can open a PR over there.

**Comment by slintes** [comment]
Thanks a lot @kunalkushwaha!

/close
