### ISSUE TITLE
Recommendation to use client-go with k8s.io v0.26.0

### ISSUE THREAD

**Issue by shahpratikr** [kubevirt/client-go#20]
We are using `kubevirt.io/client-go` package as a dependency in our project. We want to migrate our project to use `k8s.io v0.26.0`.
While compiling with k8s.io v0.26.0, we are seeing following failures related to kubevirt.io/client-go.
```
# kubevirt.io/client-go/kubecli
/cachevol/mod/kubevirt.io/client-go@v0.57.1/kubecli/kubevirt_test_utils.go:32:9: cannot use MockKubevirtClientInstance (variable of type *MockKubevirtClient) as type KubevirtClient in return statement:
	*MockKubevirtClient does not implement KubevirtClient (missing AdmissionregistrationV1alpha1 method)
```
We observed that kubevirt is using `k8s.io v0.23.5`. could you please recommend a way to use this library with k8s.io v0.26.0.
NOTE: We are seeing above error with k8s.io v0.25.0 as well.

**Comment by mhenriks** [comment]
Unfortunately, I'm not aware of any easy work around to this.  You can import `kubevirt/api` and use k8s client-gen.  Check out the README here:  https://github.com/kubevirt/api/blob/main/README.md

Another alternative is to use `kubevirt/api` along with the controller-runtime client:  https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L76-L78

**Comment by shahpratikr** [comment]
Hi @mhenriks, I have raised https://github.com/kubevirt/kubevirt/pull/9113 this PR. Can someone review this? It's a small change which fixes return type of functions.
