### ISSUE TITLE
Cannot use MockKubevirtClientInstance 

### ISSUE THREAD

**Issue by digambar15** [kubevirt/client-go#26]
# kubevirt.io/client-go/kubecli
../../go/pkg/mod/kubevirt.io/client-go@v0.59.0/kubecli/kubevirt_test_utils.go:32:9: cannot use MockKubevirtClientInstance (variable of type *MockKubevirtClient) as type KubevirtClient in return statement:
        *MockKubevirtClient does not implement KubevirtClient (missing NetworkingV1alpha1 method)

I am currently using kubevirt v0.59.0. it's all working as expected in go.mod but while building the code, it's above above issue.

**Comment by shybetheone** [comment]
我也遇到了同样的问题

**Comment by jsuwala** [comment]
This error is stopping me from using the kubevirt go client as I am getting this same error with kubevirt.io/client-go v0.56.0 as well:

The error after "go build" is:
`/Users/username/go/pkg/mod/kubevirt.io/client-go@v0.56.0/kubecli/kubevirt_test_utils.go:32:9: cannot use MockKubevirtClientInstance (variable of type *MockKubevirtClient) as KubevirtClient value in return statement: *MockKubevirtClient does not implement KubevirtClient (missing method AdmissionregistrationV1alpha1)`

If it helps, my go.mod file is:
```go
module github.com/username/backend-kubevirt

go 1.20

require (
	github.com/spf13/pflag v1.0.5
	k8s.io/apimachinery v0.27.1
	kubevirt.io/client-go v0.56.0
)

require (
	github.com/coreos/prometheus-operator v0.38.3 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/emicklei/go-restful/v3 v3.9.0 // indirect
	github.com/go-kit/kit v0.10.0 // indirect
	github.com/go-logfmt/logfmt v0.5.1 // indirect
	github.com/go-logr/logr v1.2.4 // indirect
	github.com/go-openapi/jsonpointer v0.19.5 // indirect
	github.com/go-openapi/jsonreference v0.20.0 // indirect
	github.com/go-openapi/swag v0.21.1 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/glog v1.0.0 // indirect
	github.com/golang/mock v1.6.0 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/gnostic v0.5.7-v3refs // indirect
	github.com/google/go-cmp v0.5.9 // indirect
	github.com/google/gofuzz v1.1.0 // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/gorilla/websocket v1.5.0 // indirect
	github.com/imdario/mergo v0.3.10 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111 // indirect
	github.com/kubernetes-csi/external-snapshotter/client/v4 v4.2.0 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/openshift/api v0.0.0-20230503133300-8bbcb7ca7183 // indirect
	github.com/openshift/client-go v0.0.0-20210112165513-ebc401615f47 // indirect
	github.com/openshift/custom-resource-status v1.1.2 // indirect
	github.com/pborman/uuid v1.2.1 // indirect
	golang.org/x/net v0.8.0 // indirect
	golang.org/x/oauth2 v0.0.0-20220223155221-ee480838109b // indirect
	golang.org/x/sys v0.6.0 // indirect
	golang.org/x/term v0.6.0 // indirect
	golang.org/x/text v0.8.0 // indirect
	golang.org/x/time v0.0.0-20220210224613-90d013bbcef8 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/protobuf v1.28.1 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	k8s.io/api v0.27.1 // indirect
	k8s.io/apiextensions-apiserver v0.26.3 // indirect
	k8s.io/client-go v12.0.0+incompatible // indirect
	k8s.io/klog/v2 v2.90.1 // indirect
	k8s.io/kube-openapi v0.0.0-20230501164219-8b0f38b5fd1f // indirect
	k8s.io/utils v0.0.0-20230505201702-9f6742963106 // indirect
	kubevirt.io/api v0.0.0-20230602223539-97e233db627d // indirect
	kubevirt.io/containerized-data-importer-api v1.55.2 // indirect
	kubevirt.io/controller-lifecycle-operator-sdk/api v0.0.0-20220329064328-f3cc58c6ed90 // indirect
	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.2.3 // indirect
	sigs.k8s.io/yaml v1.3.0 // indirect
)

replace (
	github.com/openshift/api => github.com/openshift/api v0.0.0-20210105115604-44119421ec6b

	k8s.io/api => k8s.io/api v0.26.3
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.26.3
	k8s.io/apimachinery => k8s.io/apimachinery v0.26.3
	k8s.io/apiserver => k8s.io/apiserver v0.26.3
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.26.3
	k8s.io/client-go => k8s.io/client-go v0.26.3
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.26.3
	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.26.3
	k8s.io/code-generator => k8s.io/code-generator v0.26.3
	k8s.io/component-base => k8s.io/component-base v0.26.3
	k8s.io/cri-api => k8s.io/cri-api v0.26.3
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.3
	k8s.io/klog => k8s.io/klog v0.4.0
	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.26.3
	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.26.3
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280
	k8s.io/kube-proxy => k8s.io/kube-proxy v0.26.3
	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.26.3
	k8s.io/kubectl => k8s.io/kubectl v0.26.3
	k8s.io/kubelet => k8s.io/kubelet v0.26.3
	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.26.3
	k8s.io/metrics => k8s.io/metrics v0.26.3
	k8s.io/node-api => k8s.io/node-api v0.26.3
	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.26.3
	k8s.io/sample-cli-plugin => k8s.io/sample-cli-plugin v0.26.3
	k8s.io/sample-controller => k8s.io/sample-controller v0.26.3
)

```

**Comment by nihargoli** [comment]
> This error is stopping me from using the kubevirt go client as I am getting this same error with kubevirt.io/client-go v0.56.0 as well:
> 
> The error after "go build" is: `/Users/username/go/pkg/mod/kubevirt.io/client-go@v0.56.0/kubecli/kubevirt_test_utils.go:32:9: cannot use MockKubevirtClientInstance (variable of type *MockKubevirtClient) as KubevirtClient value in return statement: *MockKubevirtClient does not implement KubevirtClient (missing method AdmissionregistrationV1alpha1)`
> 
> If it helps, my go.mod file is:
> 
> ```go
> module github.com/username/backend-kubevirt
> 
> go 1.20
> 
> require (
> 	github.com/spf13/pflag v1.0.5
> 	k8s.io/apimachinery v0.27.1
> 	kubevirt.io/client-go v0.56.0
> )
> 
> require (
> 	github.com/coreos/prometheus-operator v0.38.3 // indirect
> 	github.com/davecgh/go-spew v1.1.1 // indirect
> 	github.com/emicklei/go-restful/v3 v3.9.0 // indirect
> 	github.com/go-kit/kit v0.10.0 // indirect
> 	github.com/go-logfmt/logfmt v0.5.1 // indirect
> 	github.com/go-logr/logr v1.2.4 // indirect
> 	github.com/go-openapi/jsonpointer v0.19.5 // indirect
> 	github.com/go-openapi/jsonreference v0.20.0 // indirect
> 	github.com/go-openapi/swag v0.21.1 // indirect
> 	github.com/gogo/protobuf v1.3.2 // indirect
> 	github.com/golang/glog v1.0.0 // indirect
> 	github.com/golang/mock v1.6.0 // indirect
> 	github.com/golang/protobuf v1.5.2 // indirect
> 	github.com/google/gnostic v0.5.7-v3refs // indirect
> 	github.com/google/go-cmp v0.5.9 // indirect
> 	github.com/google/gofuzz v1.1.0 // indirect
> 	github.com/google/uuid v1.3.0 // indirect
> 	github.com/gorilla/websocket v1.5.0 // indirect
> 	github.com/imdario/mergo v0.3.10 // indirect
> 	github.com/josharian/intern v1.0.0 // indirect
> 	github.com/json-iterator/go v1.1.12 // indirect
> 	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111 // indirect
> 	github.com/kubernetes-csi/external-snapshotter/client/v4 v4.2.0 // indirect
> 	github.com/mailru/easyjson v0.7.7 // indirect
> 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
> 	github.com/modern-go/reflect2 v1.0.2 // indirect
> 	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
> 	github.com/openshift/api v0.0.0-20230503133300-8bbcb7ca7183 // indirect
> 	github.com/openshift/client-go v0.0.0-20210112165513-ebc401615f47 // indirect
> 	github.com/openshift/custom-resource-status v1.1.2 // indirect
> 	github.com/pborman/uuid v1.2.1 // indirect
> 	golang.org/x/net v0.8.0 // indirect
> 	golang.org/x/oauth2 v0.0.0-20220223155221-ee480838109b // indirect
> 	golang.org/x/sys v0.6.0 // indirect
> 	golang.org/x/term v0.6.0 // indirect
> 	golang.org/x/text v0.8.0 // indirect
> 	golang.org/x/time v0.0.0-20220210224613-90d013bbcef8 // indirect
> 	google.golang.org/appengine v1.6.7 // indirect
> 	google.golang.org/protobuf v1.28.1 // indirect
> 	gopkg.in/inf.v0 v0.9.1 // indirect
> 	gopkg.in/yaml.v2 v2.4.0 // indirect
> 	gopkg.in/yaml.v3 v3.0.1 // indirect
> 	k8s.io/api v0.27.1 // indirect
> 	k8s.io/apiextensions-apiserver v0.26.3 // indirect
> 	k8s.io/client-go v12.0.0+incompatible // indirect
> 	k8s.io/klog/v2 v2.90.1 // indirect
> 	k8s.io/kube-openapi v0.0.0-20230501164219-8b0f38b5fd1f // indirect
> 	k8s.io/utils v0.0.0-20230505201702-9f6742963106 // indirect
> 	kubevirt.io/api v0.0.0-20230602223539-97e233db627d // indirect
> 	kubevirt.io/containerized-data-importer-api v1.55.2 // indirect
> 	kubevirt.io/controller-lifecycle-operator-sdk/api v0.0.0-20220329064328-f3cc58c6ed90 // indirect
> 	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
> 	sigs.k8s.io/structured-merge-diff/v4 v4.2.3 // indirect
> 	sigs.k8s.io/yaml v1.3.0 // indirect
> )
> 
> replace (
> 	github.com/openshift/api => github.com/openshift/api v0.0.0-20210105115604-44119421ec6b
> 
> 	k8s.io/api => k8s.io/api v0.26.3
> 	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.26.3
> 	k8s.io/apimachinery => k8s.io/apimachinery v0.26.3
> 	k8s.io/apiserver => k8s.io/apiserver v0.26.3
> 	k8s.io/cli-runtime => k8s.io/cli-runtime v0.26.3
> 	k8s.io/client-go => k8s.io/client-go v0.26.3
> 	k8s.io/cloud-provider => k8s.io/cloud-provider v0.26.3
> 	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.26.3
> 	k8s.io/code-generator => k8s.io/code-generator v0.26.3
> 	k8s.io/component-base => k8s.io/component-base v0.26.3
> 	k8s.io/cri-api => k8s.io/cri-api v0.26.3
> 	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.26.3
> 	k8s.io/klog => k8s.io/klog v0.4.0
> 	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.26.3
> 	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.26.3
> 	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280
> 	k8s.io/kube-proxy => k8s.io/kube-proxy v0.26.3
> 	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.26.3
> 	k8s.io/kubectl => k8s.io/kubectl v0.26.3
> 	k8s.io/kubelet => k8s.io/kubelet v0.26.3
> 	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.26.3
> 	k8s.io/metrics => k8s.io/metrics v0.26.3
> 	k8s.io/node-api => k8s.io/node-api v0.26.3
> 	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.26.3
> 	k8s.io/sample-cli-plugin => k8s.io/sample-cli-plugin v0.26.3
> 	k8s.io/sample-controller => k8s.io/sample-controller v0.26.3
> )
> ```

Did you find a solution? I happen to run into same error.

**Comment by jsuwala** [comment]
I found a solution: don't use this project. And instead make your own kubevirt API client.

Following [the advice here](https://github.com/kubevirt/client-go/issues/20#issuecomment-1406579740)
1. go get kubevirt.io/api
2. use client-gen to create your own client 

Here's the shell script I used to generate my own kubevirt client:
```bash
go get kubevirt.io/api@v0.59.1 # pin the API version to the one that has been deployed on your cluster
# remove the old client that was autogenerated
rm -R ../pkg/kubevirt-client
/path/to/go/bin/client-gen --input-base="kubevirt.io/api/" --input="core/v1" --output-package="kubevirt-client" --output-base="../pkg/" --clientset-name="versioned" --go-header-file custom-boilerplate.go.txt
```
