### ISSUE TITLE
k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible

### ISSUE THREAD

**Issue by jeven2016** [kubevirt/client-go#28]
Hi team,
    I'd like to run the example 'list-vm.go' of client-go but got a blocking issue , and have no idea how to fix.  is there any suggestion on this ?  thanks.
BTW,  I use go 1.19,    

~/Desktop/backup/client-go$go mod tidy
go: finding module for package k8s.io/client-go/kubernetes/typed/discovery/v1beta1
go: finding module for package k8s.io/client-go/kubernetes/typed/certificates/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/discovery/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/admissionregistration/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/autoscaling/v2
go: finding module for package k8s.io/client-go/kubernetes/typed/events/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3
go: finding module for package k8s.io/client-go/kubernetes/typed/networking/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/node/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/policy/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/resource/v1alpha1
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: finding module for package k8s.io/apimachinery/pkg/util/clock
go: finding module for package k8s.io/api/auditregistration/v1alpha1
go: finding module for package k8s.io/api/batch/v2alpha1
go: finding module for package k8s.io/api/settings/v1alpha1
kubevirt.io/client-go/kubecli imports
        **k8s.io/client-go/kubernetes/typed/admissionregistration/v1: package k8s.io/client-go/kubernetes/typed/admissionregistration/v1 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible**
kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1: package k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible
kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1: package k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible
kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/authentication/v1alpha1: package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible
kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/autoscaling/v2: package k8s.io/client-go/kubernetes/typed/autoscaling/v2 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible
kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/certificates/v1: package k8s.io/client-go/kubernetes/typed/certificates/v1 provided by k8s.io/client-go at latest version v0.27.4 but not at required version v12.0.0+incompatible

**Comment by drssdinblck** [comment]
I can confirm the same using golang 1.20.6.

**Comment by jeven2016** [comment]
Finally, I have to generate the client by myself.   And I link my project here for reference  :  https://github.com/jeven2016/kubevirt-manager   

I generated a project named 'kubevirt.io' based on 'kubevirt/api' (https://github.com/kubevirt/api), and it now can work in go 1.19 with kubernetes v0.27.1

**Comment by Roysav** [comment]
Same here, currently unusable

**Comment by yavidor** [comment]
Also here

**Comment by jeven2016** [comment]
any updates?

**Comment by drssdinblck** [comment]
I suspect this is not going to be fixed anymore. Probably the standard way now is to use the [API project](https://github.com/kubevirt/api) and generate the client using the [Kubernetes client code generator](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen). I followed the documentation in the [API project](https://github.com/kubevirt/api) and got it working.

**Comment by yavidor** [comment]
Can you share it?

**Comment by jeven2016** [comment]
> I suspect this is not going to be fixed anymore. Probably the standard way now is to use the [API project](https://github.com/kubevirt/api) and generate the client using the [Kubernetes client code generator](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen). I followed the documentation in the [API project](https://github.com/kubevirt/api) and got it working for kubevirt and [CDI](https://github.com/kubevirt/containerized-data-importer-api).

did you port 'kubecli' into your project? I still encounter such problem after copied the kubecli package from client-go into my project.

**Comment by mtaylor91** [comment]
I was able to generate the client using `client-gen`, however it seems it doesn't include the `Start`/`Stop` methods.

Seems like a bit of a sub-optimal solution.  If generating the client is the recommended path forward, is the recommended way to handle start/stop actions just to patch the `VirtualMachine.Spec.Running` field?  Or is there a straightforward way to support the `Start`/`Stop` methods in the generated client?  Or will this issue (module imports) be fixed in `kubevirt/client-go`?

**Comment by jeven2016** [comment]
> > I suspect this is not going to be fixed anymore. Probably the standard way now is to use the [API project](https://github.com/kubevirt/api) and generate the client using the [Kubernetes client code generator](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen). I followed the documentation in the [API project](https://github.com/kubevirt/api) and got it working for kubevirt and [CDI](https://github.com/kubevirt/containerized-data-importer-api).
> 
> I was able to generate the client using `client-gen`, however it seems it doesn't include the `Start`/`Stop` methods.
> 
> Seems like a bit of a sub-optimal solution. If generating the client is the recommended path forward, is the recommended way to handle start/stop actions just to patch the `VirtualMachine.Spec.Running` field? Or is there a straightforward way to support the `Start`/`Stop` methods in the generated client? Or will this issue (module imports) be fixed in `kubevirt/client-go`?

I think you have to directly call the rest api after checked the code of kubecli,  the below code I currently used can work as expected:

VmSubresourceURLFmt = "/apis/subresources.kubevirt.io/%s/namespaces/%s/virtualmachines/%s/%s"

// invoke rest api to start a VMI
func (v *VmManager) start(ctx context.Context, namespace string, name string, startOptions *kv1.StartOptions) error {
	uri := fmt.Sprintf(constants.VmSubresourceURLFmt, kv1.ApiStorageVersion, namespace, name, "start")

	optsJson, err := json.Marshal(startOptions)
	if err != nil {
		return err
	}
        // here kvClient  is  *versioned.Clientset 
	return v.kvClient.RESTClient().Put().AbsPath(uri).Body(optsJson).Do(ctx).Error()
}

// invoke rest api to stop a VMI
func (v *VmManager) stop(ctx context.Context, namespace string, name string, stopOptions *kv1.StopOptions) error {
	uri := fmt.Sprintf(constants.VmSubresourceURLFmt, kv1.ApiStorageVersion, namespace, name, "stop")
	optsJson, err := json.Marshal(stopOptions)
	if err != nil {
		return err
	}
	return v.kvClient.RESTClient().Put().AbsPath(uri).Body(optsJson).Do(ctx).Error()
}

**Comment by drssdinblck** [comment]
> > I suspect this is not going to be fixed anymore. Probably the standard way now is to use the [API project](https://github.com/kubevirt/api) and generate the client using the [Kubernetes client code generator](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen). I followed the documentation in the [API project](https://github.com/kubevirt/api) and got it working for kubevirt and [CDI](https://github.com/kubevirt/containerized-data-importer-api).
> 
> did you port 'kubecli' into your project? I still encounter such problem after copied the kubecli package from client-go into my project.

No, what I did is follow the instructions from https://github.com/kubevirt/api. Namely, first install the `client-gen` binary via
```shell
go install k8s.io/code-generator/cmd/client-gen@latest
```

Then add the API project as a dependency to your project
```shell
go get kubevirt.io/api
```

Then run the code generator
```shell
client-gen --input-base="kubevirt.io/api/" --input="core/v1" --output-package="testapi/client" --output-base="../" --clientset-name="versioned" --go-header-file boilerplate.go.txt
```
Then you can use the generated API client in your code.

**Comment by yavidor** [comment]
How do I reference it in my code instead of the normal api?

**Comment by yavidor** [comment]
> > > I suspect this is not going to be fixed anymore. Probably the standard way now is to use the [API project](https://github.com/kubevirt/api) and generate the client using the [Kubernetes client code generator](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen). I followed the documentation in the [API project](https://github.com/kubevirt/api) and got it working for kubevirt and [CDI](https://github.com/kubevirt/containerized-data-importer-api).
> > 
> > 
> > did you port 'kubecli' into your project? I still encounter such problem after copied the kubecli package from client-go into my project.
> 
> No, what I did is follow the instructions from https://github.com/kubevirt/api. Namely, first install the `client-gen` binary via
> 
> ```shell
> go install k8s.io/code-generator/cmd/client-gen@latest
> ```
> 
> Then add the API project as a dependency to your project
> 
> ```shell
> go get kubevirt.io/api
> ```
> 
> Then run the code generator
> 
> ```shell
> client-gen --input-base="kubevirt.io/api/" --input="core/v1" --output-package="testapi/client" --output-base="../" --clientset-name="versioned" --go-header-file boilerplate.go.txt
> ```
> 
> Then you can use the generated API client in your code.

How do I reference it in my code instead of the normal package?
